title: "Haas Capital"
author: Haas Capital
email: "hello@haas.capital"
description: "Haas Capital is a venture firm which invests in early-stage productivity and security software"
github: haas.capital
highlighter: rouge
markdown: kramdown
parse_block_html: false
url: https://haas.capital
permalink: blog/:title
timezome: America/Los Angeles
show_drafts: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      layout: post

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page


collections:
  pages:
    output: true

plugins:
  - jekyll-feed
